GET http://localhost:5000/

###

GET http://localhost:5000/api/auth/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTQzNmQ5NGQ5ZTliMDI4OWE4MDI5NWYiLCJpYXQiOjE2MzE4MDg5MTZ9.v03yQxR2mddnYboJPfNuYz4iZ4teXP8uygkU0GSgA74

###

POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "sanguyen",
  "email": "sanguyen@gmail.com",
  "password": "sanguyen"
  
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "chungnguyen@gmail.com",
  "password": "chungnguyen"
  
}

###

#chungnguyen get the room list
GET http://localhost:5000/api/rooms
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTRlZTY5ODgzNzQ4NjdjYzMwN2ExYmIiLCJpYXQiOjE2MzI1NjEzNDR9.7G3mCtftuckxRzFVVyUqMfExBVWybln-6q4O5CsjCGY

###

#ninhphan create room
POST http://localhost:5000/api/rooms
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTRlZTZhODgzNzQ4NjdjYzMwN2ExYmUiLCJpYXQiOjE2MzI1NjEwMTN9.uT5W5KBTUMHpLE-Yxb1yI8uSNwhWXzeGZcJFvkPFznw

{
  "roomName": "CSS",
  "desc": "CSS study"  
}

###

#ninhphan update
PUT http://localhost:5000/api/rooms/614ee7c98374867cc307a1dd
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTRlZTZhODgzNzQ4NjdjYzMwN2ExYmUiLCJpYXQiOjE2MzI1NjEwMTN9.uT5W5KBTUMHpLE-Yxb1yI8uSNwhWXzeGZcJFvkPFznw

{
  "roomName": "ExpressJs",
  "desc": "ExpressJs study"  
}

###

#ninhphan delete
DELETE http://localhost:5000/api/rooms/614ee85f8374867cc307a1ea
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTRlZTZhODgzNzQ4NjdjYzMwN2ExYmUiLCJpYXQiOjE2MzI1NjEwMTN9.uT5W5KBTUMHpLE-Yxb1yI8uSNwhWXzeGZcJFvkPFznw

###

#chungnguyen get messages
GET http://localhost:5000/api/messages/614ee7218374867cc307a1d0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTRlZTY5ODgzNzQ4NjdjYzMwN2ExYmIiLCJpYXQiOjE2MzI1NjEzNDR9.7G3mCtftuckxRzFVVyUqMfExBVWybln-6q4O5CsjCGY

###

#send messages
POST http://localhost:5000/api/messages/614ee7218374867cc307a1d0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTRlZTZhODgzNzQ4NjdjYzMwN2ExYmUiLCJpYXQiOjE2MzQyMDE3NzV9.T3NP46QuIiSInbo9u3TDNgXl1Z0ynyWSh26fsi4IxDg

{
  "text": "When should we start?"
}

###

#search User
GET http://localhost:5000/api/search/users?q=va
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTRlZTY5ODgzNzQ4NjdjYzMwN2ExYmIiLCJpYXQiOjE2MzU1MDI5NjF9.pYW6kfZxA9fsYSJQnQ7mP1EtjU83r-gcOrCwUzgOiwc


###

#search Room
GET http://localhost:5000/api/search/rooms?q=rea
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTRlZTY5ODgzNzQ4NjdjYzMwN2ExYmIiLCJpYXQiOjE2MzQyODgwOTF9.AO--eGoc-uXPiSsB_xLQ6PuUflPz28GfgR9IcOC-OEk

###

#Add member to a room
PUT http://localhost:5000/api/rooms/invite/614ee7218374867cc307a1d0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTRlZTY5ODgzNzQ4NjdjYzMwN2ExYmIiLCJpYXQiOjE2MzQyODgwOTF9.AO--eGoc-uXPiSsB_xLQ6PuUflPz28GfgR9IcOC-OEk

{
  "userIds": ["614ee6c08374867cc307a1c4", "6167eea329950156f1ca6080"]
}

